In [1]:
import torch
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
print(torch.__version__)

2.8.0+cu126


In [2]:
# Creating a Scalar
s= torch.tensor(3)
s

tensor(3)

In [3]:
s.ndim

0

In [4]:
# Creating a Vector
v= torch.tensor([1,3])
v

tensor([1, 3])

In [5]:
v.ndim

1

In [6]:
v.shape

torch.Size([2])

In [7]:
# Creating a Matrix
M = torch.tensor([[1,4],
                  [3,8]])
M

tensor([[1, 4],
        [3, 8]])

In [8]:
M.ndim

2

In [9]:
M[1]

tensor([3, 8])

In [10]:
M.shape

torch.Size([2, 2])

In [11]:
# Creating a Tensor
T= torch.tensor([[[1,4,6],[2,60,2]],
                 [[12,47,56],[21,650,23]]])
T

tensor([[[  1,   4,   6],
         [  2,  60,   2]],

        [[ 12,  47,  56],
         [ 21, 650,  23]]])

In [12]:
T.ndim

3

In [13]:
T.shape

torch.Size([2, 2, 3])

In [14]:
T[1,0]

tensor([12, 47, 56])

In [15]:
import random

In [16]:
# Generating Tensor with random integers
TDT= torch.tensor([[[random.randint(1,100) for i in range(10)]for j in range(10)]for k in range(3)])

In [17]:
TDT

tensor([[[100,  59,  49,  64,  98,  91,  96,  36,  36,   4],
         [ 66,  59,   3,  43,  21,  30,  53,  26,  23,  90],
         [ 66,  82,  35,  92,  64,  44,   9,  73,   1,  92],
         [ 43,  92,  50,  63,  32,  47,  22,  30,  93,  45],
         [ 16,  61,  57,   6,  40,  65,  31,  46,  21,  38],
         [ 57,  67,  85,  59,  36,  61,  37,  66,  87,  52],
         [ 88,  91,  36,  68,  16,   1,  41,  51,  99,  17],
         [  5,  65,  16,  78,  91,   2,  48,   4,  21,  52],
         [ 37,  75,   2,  85,  25,  70,  13,   2,  59,  48],
         [ 67,  25,   2,  98,  30,  88,  32,  37,  90,  29]],

        [[ 31,  80,  60,  31,  99,  83,  70,  35,  24,  19],
         [ 72,  37,  50,  14,  53,  88,  49,  12,  48,  31],
         [ 33,  90,   2,  57,  86,  39,   1,  27,  50,  10],
         [ 30,  34,  28,  33,  22,  31,  94,  83,  63,  84],
         [ 48,  17,  20,  75,  22,  82,  43,  23,  16,  26],
         [ 52,  57,  58,  98,  61,  82,  39,  85,  41,  48],
         [ 98,  27,  3

In [18]:
TDT.shape

torch.Size([3, 10, 10])

In [19]:
TDT.ndim

3

In [20]:
#Generating random numbers in Tensor
torch.rand(2,2,3,4,10)

tensor([[[[[6.1461e-01, 6.5172e-01, 6.9887e-01, 2.4132e-01, 1.5408e-02,
            6.2119e-01, 3.0361e-01, 1.2689e-02, 7.0363e-01, 1.8731e-01],
           [9.9328e-01, 1.1928e-01, 3.3717e-01, 3.5828e-04, 6.9427e-01,
            5.4480e-01, 7.4991e-01, 6.8725e-01, 1.6427e-01, 4.8366e-01],
           [5.0447e-01, 7.1271e-01, 7.2529e-01, 6.1103e-01, 2.0253e-01,
            9.8321e-01, 5.0469e-01, 8.0110e-01, 1.7621e-01, 2.8257e-01],
           [5.4053e-01, 1.6745e-01, 6.9457e-01, 2.0745e-02, 1.6069e-01,
            6.2568e-01, 2.2423e-01, 5.9999e-01, 6.5372e-01, 2.1998e-01]],

          [[2.9018e-01, 7.3222e-01, 8.0395e-01, 4.6083e-01, 8.6887e-01,
            1.2763e-01, 4.4506e-01, 4.0412e-01, 6.4852e-01, 2.5873e-02],
           [5.1764e-01, 3.9790e-01, 9.9637e-02, 6.5497e-01, 7.5965e-01,
            2.1620e-01, 3.1425e-01, 9.4454e-01, 8.2253e-01, 2.3678e-01],
           [4.1135e-01, 8.0642e-01, 8.1391e-01, 6.5630e-01, 1.3445e-01,
            5.8816e-01, 1.4188e-01, 6.1353e-01, 2.1491e-

In [21]:
# Generating Tensors using arange
T1= torch.arange(120).reshape(3,2,2,10)

In [22]:
T1

tensor([[[[  0,   1,   2,   3,   4,   5,   6,   7,   8,   9],
          [ 10,  11,  12,  13,  14,  15,  16,  17,  18,  19]],

         [[ 20,  21,  22,  23,  24,  25,  26,  27,  28,  29],
          [ 30,  31,  32,  33,  34,  35,  36,  37,  38,  39]]],


        [[[ 40,  41,  42,  43,  44,  45,  46,  47,  48,  49],
          [ 50,  51,  52,  53,  54,  55,  56,  57,  58,  59]],

         [[ 60,  61,  62,  63,  64,  65,  66,  67,  68,  69],
          [ 70,  71,  72,  73,  74,  75,  76,  77,  78,  79]]],


        [[[ 80,  81,  82,  83,  84,  85,  86,  87,  88,  89],
          [ 90,  91,  92,  93,  94,  95,  96,  97,  98,  99]],

         [[100, 101, 102, 103, 104, 105, 106, 107, 108, 109],
          [110, 111, 112, 113, 114, 115, 116, 117, 118, 119]]]])

In [23]:
# Create a tensor of all zeros
zeros = torch.zeros(3, 4)
zeros, zeros.dtype

(tensor([[0., 0., 0., 0.],
         [0., 0., 0., 0.],
         [0., 0., 0., 0.]]),
 torch.float32)

In [24]:
# Create a tensor of all ones
ones = torch.ones(3, 4)
ones, ones.dtype

(tensor([[1., 1., 1., 1.],
         [1., 1., 1., 1.],
         [1., 1., 1., 1.]]),
 torch.float32)

In [25]:
# Create a range of values 0 to 1000
ztt = torch.arange(start=0, end=1000, step=1)
ztt

tensor([  0,   1,   2,   3,   4,   5,   6,   7,   8,   9,  10,  11,  12,  13,
         14,  15,  16,  17,  18,  19,  20,  21,  22,  23,  24,  25,  26,  27,
         28,  29,  30,  31,  32,  33,  34,  35,  36,  37,  38,  39,  40,  41,
         42,  43,  44,  45,  46,  47,  48,  49,  50,  51,  52,  53,  54,  55,
         56,  57,  58,  59,  60,  61,  62,  63,  64,  65,  66,  67,  68,  69,
         70,  71,  72,  73,  74,  75,  76,  77,  78,  79,  80,  81,  82,  83,
         84,  85,  86,  87,  88,  89,  90,  91,  92,  93,  94,  95,  96,  97,
         98,  99, 100, 101, 102, 103, 104, 105, 106, 107, 108, 109, 110, 111,
        112, 113, 114, 115, 116, 117, 118, 119, 120, 121, 122, 123, 124, 125,
        126, 127, 128, 129, 130, 131, 132, 133, 134, 135, 136, 137, 138, 139,
        140, 141, 142, 143, 144, 145, 146, 147, 148, 149, 150, 151, 152, 153,
        154, 155, 156, 157, 158, 159, 160, 161, 162, 163, 164, 165, 166, 167,
        168, 169, 170, 171, 172, 173, 174, 175, 176, 177, 178, 1

In [26]:
# Can also create a tensor of zeros similar to another tensor
tz = torch.zeros_like(input=ztt)
tz

tensor([0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
        0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
        0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
        0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
        0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
        0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
        0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
        0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
        0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
        0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
        0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
        0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
        0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,

In [27]:
# Can also create a tensor of ones similar to another tensor
to = torch.ones_like(input=ztt)
to

tensor([1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
        1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
        1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
        1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
        1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
        1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
        1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
        1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
        1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
        1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
        1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
        1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
        1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,

In [28]:
# Default datatype for tensors is float32
float_32_tensor = torch.tensor([3.0, 6.0, 9.0],
                               dtype=None, # defaults to None, which is torch.float32 or whatever datatype is passed
                               device=None, # defaults to None, which uses the default tensor type
                               requires_grad=False) # if True, operations performed on the tensor are recorded

float_32_tensor.shape, float_32_tensor.dtype, float_32_tensor.device

(torch.Size([3]), torch.float32, device(type='cpu'))

In [29]:
float_16_tensor = torch.tensor([3.0, 6.0, 9.0],
                               dtype=torch.float16) # torch.half would also work

float_16_tensor.dtype

torch.float16

In [30]:
# Multiplication
t2=torch.tensor([1, 2, 3])
t2*t2

tensor([1, 4, 9])

In [31]:
torch.matmul(t2,t2)

tensor(14)