In [ ]:
import torch
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
print(torch.__version__)

2.8.0+cu126


In [ ]:
# Creating a Scalar
s= torch.tensor(3)
s

tensor(3)

In [ ]:
s.ndim

0

In [ ]:
# Creating a Vector
v= torch.tensor([1,3])
v

tensor([1, 3])

In [ ]:
v.ndim

1

In [ ]:
v.shape

torch.Size([2])

In [ ]:
# Creating a Matrix
M = torch.tensor([[1,4],
                  [3,8]])
M

tensor([[1, 4],
        [3, 8]])

In [ ]:
M.ndim

2

In [ ]:
M[1]

tensor([3, 8])

In [ ]:
M.shape

torch.Size([2, 2])

In [ ]:
# Creating a Tensor
T= torch.tensor([[[1,4,6],[2,60,2]],
                 [[12,47,56],[21,650,23]]])
T

tensor([[[  1,   4,   6],
         [  2,  60,   2]],

        [[ 12,  47,  56],
         [ 21, 650,  23]]])

In [ ]:
T.ndim

3

In [ ]:
T.shape

torch.Size([2, 2, 3])

In [ ]:
T[1,0]

tensor([12, 47, 56])

In [ ]:
import random

In [52]:
# Generating Tensor with random integers
TDT= torch.tensor([[[random.randint(1,100) for i in range(10)]for j in range(10)]for k in range(3)])

In [53]:
TDT

tensor([[[ 43,  13,  70,  81,  93,  15,  17,  86,  28,   2],
         [ 14,  40,  62,   6,  13,  44,   7,   8,  53,  49],
         [ 11,  98,   1,  87,  60,  27,   4,  17,  55,   9],
         [ 45,  28,  33,  20,  11,  84,  70,  92,  33,  31],
         [ 76,  64,  66,  69,  66,  68,  92,  41,  88,  44],
         [ 55,  52,  80,  51,  46,  59,  41,  93,  39,  84],
         [ 40,  84,  37,  13,  40,  29,  80,  33,  39,  83],
         [ 80,  23,  60,  84,  91,  95,  68,  13,  38,  60],
         [ 46,  70,   3,  60,  84,  44,  46,  98,  88,  27],
         [ 11,  49,   8,  30,  89,  56,  96,  18,  78,  89]],

        [[  7,  23,  83,  16,  68,  63,  82,  88,  68,  83],
         [ 48,  40,  75,  14,  40,  85,  62, 100,   2,  47],
         [ 40,  94,   1,  71,  32,  24,   4, 100,  84,  72],
         [ 49,  66,  93,  12,  28,  38,  29,  47,  47,  58],
         [ 80,  90,  81,  26,  53,   1,  31,  82,  14,  76],
         [ 53,  70,  37,  17,  66,  36,  47,  87,  94,  57],
         [ 70,  93,  3

In [54]:
TDT.shape

torch.Size([3, 10, 10])

In [56]:
TDT.ndim

3

In [42]:
#Generating random numbers in Tensor
torch.rand(2,2,3,4,10)

tensor([[[[[2.3338e-01, 4.0779e-02, 4.1861e-02, 9.4066e-01, 4.6306e-01,
            8.3668e-01, 7.2950e-02, 4.6609e-01, 2.9409e-01, 7.8605e-01],
           [2.7252e-02, 7.5268e-01, 8.2054e-01, 5.6816e-01, 3.9012e-01,
            4.7676e-01, 4.4422e-01, 4.9040e-01, 8.1429e-01, 6.0086e-01],
           [5.4906e-02, 2.8013e-01, 6.3274e-01, 5.8241e-01, 6.7168e-01,
            1.3242e-01, 5.9149e-01, 3.4337e-01, 3.8808e-01, 2.0410e-01],
           [4.5202e-01, 5.5808e-01, 1.4980e-01, 7.7579e-01, 4.1398e-01,
            9.8998e-01, 4.6151e-01, 2.8418e-01, 8.6901e-01, 6.5689e-01]],

          [[9.5811e-01, 9.9219e-01, 6.4501e-01, 3.0937e-01, 3.9037e-01,
            3.5116e-01, 5.8154e-01, 5.2228e-01, 7.4845e-01, 5.1021e-01],
           [5.6259e-02, 4.8638e-01, 1.5168e-01, 1.2169e-01, 3.4148e-01,
            3.5325e-03, 3.7044e-01, 9.8719e-01, 9.4100e-01, 4.5299e-01],
           [2.2079e-01, 8.3560e-01, 9.3008e-01, 9.2868e-01, 7.1455e-02,
            7.6047e-01, 3.5389e-01, 7.0419e-01, 7.0748e-

In [58]:
# Generating Tensors using arange
T1= torch.arange(120).reshape(3,2,2,10)

In [59]:
T1

tensor([[[[  0,   1,   2,   3,   4,   5,   6,   7,   8,   9],
          [ 10,  11,  12,  13,  14,  15,  16,  17,  18,  19]],

         [[ 20,  21,  22,  23,  24,  25,  26,  27,  28,  29],
          [ 30,  31,  32,  33,  34,  35,  36,  37,  38,  39]]],


        [[[ 40,  41,  42,  43,  44,  45,  46,  47,  48,  49],
          [ 50,  51,  52,  53,  54,  55,  56,  57,  58,  59]],

         [[ 60,  61,  62,  63,  64,  65,  66,  67,  68,  69],
          [ 70,  71,  72,  73,  74,  75,  76,  77,  78,  79]]],


        [[[ 80,  81,  82,  83,  84,  85,  86,  87,  88,  89],
          [ 90,  91,  92,  93,  94,  95,  96,  97,  98,  99]],

         [[100, 101, 102, 103, 104, 105, 106, 107, 108, 109],
          [110, 111, 112, 113, 114, 115, 116, 117, 118, 119]]]])