In [1]:
import torch
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
print(torch.__version__)

2.8.0+cu126


In [2]:
# Creating a Scalar
s= torch.tensor(3)
s

tensor(3)

In [3]:
s.ndim

0

In [4]:
# Creating a Vector
v= torch.tensor([1,3])
v

tensor([1, 3])

In [5]:
v.ndim

1

In [6]:
v.shape

torch.Size([2])

In [7]:
# Creating a Matrix
M = torch.tensor([[1,4],
                  [3,8]])
M

tensor([[1, 4],
        [3, 8]])

In [8]:
M.ndim

2

In [9]:
M[1]

tensor([3, 8])

In [10]:
M.shape

torch.Size([2, 2])

In [11]:
# Creating a Tensor
T= torch.tensor([[[1,4,6],[2,60,2]],
                 [[12,47,56],[21,650,23]]])
T

tensor([[[  1,   4,   6],
         [  2,  60,   2]],

        [[ 12,  47,  56],
         [ 21, 650,  23]]])

In [12]:
T.ndim

3

In [13]:
T.shape

torch.Size([2, 2, 3])

In [14]:
T[1,0]

tensor([12, 47, 56])

In [15]:
import random

In [16]:
# Generating Tensor with random integers
TDT= torch.tensor([[[random.randint(1,100) for i in range(10)]for j in range(10)]for k in range(3)])

In [17]:
TDT

tensor([[[ 41,   9,  65,  84,   8,  28,  50,  91,  39,   9],
         [ 65,  52,  63,  93,  84,  18,  31,   3,  32,  74],
         [ 58,  23,  15,   1,  55,  37,  26,  39,  47,  98],
         [ 70,  89,  18,  84,  22,   3,  45,  71,  77,  28],
         [  1,  66,  64,  80,  39,   7,  11,  33,  90,  38],
         [ 93,  63,  33,  28,  56,  85,  31,  17,  10,  39],
         [ 29,  40,  37,  49,  27,  63,  69,  62,   6,  21],
         [ 15,  57,  43,  18,  87,   8,  63,   5,  88,  23],
         [ 78,   8,  99,  72,  87,  66,  83,  44,  20,  62],
         [ 48,  43,  98,  72,  17,  55,  86,   5,  69,  70]],

        [[  6,  63,  42,  12,  50,   5,  30,  57,  19,   4],
         [ 81,  27,  78,  65,  38,  60,  69,  62,  60,  46],
         [ 31,  52,  23,  45,  30,  40,  67,  76, 100,  54],
         [ 10,  14,  91,  53,   9,   9,  63,  60, 100,  40],
         [ 69,  72,  33,  16,  82,  30,  44,  11,  78,  32],
         [  1,  62,  58,  74,  52,  71,  38,  82,  14,  59],
         [ 36,   4,  8

In [18]:
TDT.shape

torch.Size([3, 10, 10])

In [19]:
TDT.ndim

3

In [20]:
#Generating random numbers in Tensor
torch.rand(2,2,3,4,10)

tensor([[[[[0.9579, 0.0619, 0.5415, 0.6956, 0.5072, 0.0376, 0.3622, 0.1944,
            0.3079, 0.8981],
           [0.8252, 0.9286, 0.4086, 0.6719, 0.8919, 0.2283, 0.3843, 0.7212,
            0.4993, 0.8825],
           [0.8757, 0.1299, 0.0480, 0.4208, 0.6920, 0.1923, 0.6732, 0.5475,
            0.7076, 0.2714],
           [0.3892, 0.3022, 0.6845, 0.0306, 0.8231, 0.1274, 0.6754, 0.5154,
            0.3437, 0.2068]],

          [[0.1104, 0.9715, 0.7891, 0.9662, 0.2520, 0.8897, 0.6936, 0.7522,
            0.6082, 0.0959],
           [0.8743, 0.4759, 0.5175, 0.6943, 0.3941, 0.7511, 0.3134, 0.9789,
            0.5149, 0.4189],
           [0.4838, 0.9350, 0.0887, 0.2170, 0.7369, 0.0181, 0.0181, 0.2947,
            0.9402, 0.4205],
           [0.6339, 0.1979, 0.9546, 0.0581, 0.3416, 0.7365, 0.2437, 0.0100,
            0.5145, 0.2721]],

          [[0.3720, 0.3278, 0.4072, 0.8974, 0.3993, 0.5477, 0.1522, 0.9166,
            0.8368, 0.6326],
           [0.3031, 0.3153, 0.9310, 0.3063, 0.0451,

In [21]:
# Generating Tensors using arange
T1= torch.arange(120).reshape(3,2,2,10)

In [22]:
T1

tensor([[[[  0,   1,   2,   3,   4,   5,   6,   7,   8,   9],
          [ 10,  11,  12,  13,  14,  15,  16,  17,  18,  19]],

         [[ 20,  21,  22,  23,  24,  25,  26,  27,  28,  29],
          [ 30,  31,  32,  33,  34,  35,  36,  37,  38,  39]]],


        [[[ 40,  41,  42,  43,  44,  45,  46,  47,  48,  49],
          [ 50,  51,  52,  53,  54,  55,  56,  57,  58,  59]],

         [[ 60,  61,  62,  63,  64,  65,  66,  67,  68,  69],
          [ 70,  71,  72,  73,  74,  75,  76,  77,  78,  79]]],


        [[[ 80,  81,  82,  83,  84,  85,  86,  87,  88,  89],
          [ 90,  91,  92,  93,  94,  95,  96,  97,  98,  99]],

         [[100, 101, 102, 103, 104, 105, 106, 107, 108, 109],
          [110, 111, 112, 113, 114, 115, 116, 117, 118, 119]]]])

In [23]:
# Create a tensor of all zeros
zeros = torch.zeros(3, 4)
zeros, zeros.dtype

(tensor([[0., 0., 0., 0.],
         [0., 0., 0., 0.],
         [0., 0., 0., 0.]]),
 torch.float32)

In [24]:
# Create a tensor of all ones
ones = torch.ones(3, 4)
ones, ones.dtype

(tensor([[1., 1., 1., 1.],
         [1., 1., 1., 1.],
         [1., 1., 1., 1.]]),
 torch.float32)

In [25]:
# Create a range of values 0 to 1000
ztt = torch.arange(start=0, end=1000, step=1)
ztt

tensor([  0,   1,   2,   3,   4,   5,   6,   7,   8,   9,  10,  11,  12,  13,
         14,  15,  16,  17,  18,  19,  20,  21,  22,  23,  24,  25,  26,  27,
         28,  29,  30,  31,  32,  33,  34,  35,  36,  37,  38,  39,  40,  41,
         42,  43,  44,  45,  46,  47,  48,  49,  50,  51,  52,  53,  54,  55,
         56,  57,  58,  59,  60,  61,  62,  63,  64,  65,  66,  67,  68,  69,
         70,  71,  72,  73,  74,  75,  76,  77,  78,  79,  80,  81,  82,  83,
         84,  85,  86,  87,  88,  89,  90,  91,  92,  93,  94,  95,  96,  97,
         98,  99, 100, 101, 102, 103, 104, 105, 106, 107, 108, 109, 110, 111,
        112, 113, 114, 115, 116, 117, 118, 119, 120, 121, 122, 123, 124, 125,
        126, 127, 128, 129, 130, 131, 132, 133, 134, 135, 136, 137, 138, 139,
        140, 141, 142, 143, 144, 145, 146, 147, 148, 149, 150, 151, 152, 153,
        154, 155, 156, 157, 158, 159, 160, 161, 162, 163, 164, 165, 166, 167,
        168, 169, 170, 171, 172, 173, 174, 175, 176, 177, 178, 1

In [26]:
# Can also create a tensor of zeros similar to another tensor
tz = torch.zeros_like(input=ztt)
tz

tensor([0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
        0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
        0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
        0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
        0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
        0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
        0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
        0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
        0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
        0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
        0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
        0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
        0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,

In [27]:
# Can also create a tensor of ones similar to another tensor
to = torch.ones_like(input=ztt)
to

tensor([1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
        1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
        1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
        1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
        1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
        1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
        1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
        1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
        1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
        1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
        1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
        1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
        1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,

In [28]:
# Default datatype for tensors is float32
float_32_tensor = torch.tensor([3.0, 6.0, 9.0],
                               dtype=None, # defaults to None, which is torch.float32 or whatever datatype is passed
                               device=None, # defaults to None, which uses the default tensor type
                               requires_grad=False) # if True, operations performed on the tensor are recorded

float_32_tensor.shape, float_32_tensor.dtype, float_32_tensor.device

(torch.Size([3]), torch.float32, device(type='cpu'))

In [29]:
float_16_tensor = torch.tensor([3.0, 6.0, 9.0],
                               dtype=torch.float16) # torch.half would also work

float_16_tensor.dtype

torch.float16

In [30]:
# Multiplication
t2=torch.tensor([1, 2, 3])
t2*t2

tensor([1, 4, 9])

In [31]:
torch.matmul(t2,t2)

tensor(14)

In [33]:
# We can also do matrix multiplication by @
t2 @ t2

tensor(14)

In [36]:
# Transpose
T1.T

/tmp/ipython-input-1193103756.py:2: UserWarning: The use of `x.T` on tensors of dimension other than 2 to reverse their shape is deprecated and it will throw an error in a future release. Consider `x.mT` to transpose batches of matrices or `x.permute(*torch.arange(x.ndim - 1, -1, -1))` to reverse the dimensions of a tensor. (Triggered internally at /pytorch/aten/src/ATen/native/TensorShape.cpp:4421.)
  T1.T


tensor([[[[  0,  40,  80],
          [ 20,  60, 100]],

         [[ 10,  50,  90],
          [ 30,  70, 110]]],


        [[[  1,  41,  81],
          [ 21,  61, 101]],

         [[ 11,  51,  91],
          [ 31,  71, 111]]],


        [[[  2,  42,  82],
          [ 22,  62, 102]],

         [[ 12,  52,  92],
          [ 32,  72, 112]]],


        [[[  3,  43,  83],
          [ 23,  63, 103]],

         [[ 13,  53,  93],
          [ 33,  73, 113]]],


        [[[  4,  44,  84],
          [ 24,  64, 104]],

         [[ 14,  54,  94],
          [ 34,  74, 114]]],


        [[[  5,  45,  85],
          [ 25,  65, 105]],

         [[ 15,  55,  95],
          [ 35,  75, 115]]],


        [[[  6,  46,  86],
          [ 26,  66, 106]],

         [[ 16,  56,  96],
          [ 36,  76, 116]]],


        [[[  7,  47,  87],
          [ 27,  67, 107]],

         [[ 17,  57,  97],
          [ 37,  77, 117]]],


        [[[  8,  48,  88],
          [ 28,  68, 108]],

         [[ 18,  58,  98],
     

torch.mm is a shortcut for matmul

In [37]:
# max, min, mean, sum, etc
x = torch.arange(0, 100, 10)
x
print(f"Minimum: {x.min()}")
print(f"Maximum: {x.max()}")
# print(f"Mean: {x.mean()}") # this will error
print(f"Mean: {x.type(torch.float32).mean()}") # won't work without float datatype
print(f"Sum: {x.sum()}")

Minimum: 0
Maximum: 90
Mean: 45.0
Sum: 450


In [38]:
# Positional min, max
tensor = torch.arange(10, 100, 10)
print(f"Tensor: {tensor}")

# Returns index of max and min values
print(f"Index where max value occurs: {tensor.argmax()}")
print(f"Index where min value occurs: {tensor.argmin()}")

Tensor: tensor([10, 20, 30, 40, 50, 60, 70, 80, 90])
Index where max value occurs: 8
Index where min value occurs: 0


In [41]:
# Add an extra dimension
x = torch.arange(1., 8.)
x, x.shape
x_reshaped = x.reshape(1, 7)
x_reshaped, x_reshaped.shape

(tensor([[1., 2., 3., 4., 5., 6., 7.]]), torch.Size([1, 7]))

In [42]:
# Change view (keeps same data as original but changes view)
z = x.view(1, 7)
z, z.shape

(tensor([[1., 2., 3., 4., 5., 6., 7.]]), torch.Size([1, 7]))

In [43]:
# Changing z changes x
z[:, 0] = 5
z, x

(tensor([[5., 2., 3., 4., 5., 6., 7.]]), tensor([5., 2., 3., 4., 5., 6., 7.]))

In [44]:
# Stack tensors on top of each other
x_stacked = torch.stack([x, x, x, x], dim=0)
x_stacked

tensor([[5., 2., 3., 4., 5., 6., 7.],
        [5., 2., 3., 4., 5., 6., 7.],
        [5., 2., 3., 4., 5., 6., 7.],
        [5., 2., 3., 4., 5., 6., 7.]])

In [45]:
print(f"Previous tensor: {x_reshaped}")
print(f"Previous shape: {x_reshaped.shape}")

# Remove extra dimension from x_reshaped
x_squeezed = x_reshaped.squeeze()
print(f"\nNew tensor: {x_squeezed}")
print(f"New shape: {x_squeezed.shape}")

Previous tensor: tensor([[5., 2., 3., 4., 5., 6., 7.]])
Previous shape: torch.Size([1, 7])

New tensor: tensor([5., 2., 3., 4., 5., 6., 7.])
New shape: torch.Size([7])


In [46]:
print(f"Previous tensor: {x_squeezed}")
print(f"Previous shape: {x_squeezed.shape}")

## Add an extra dimension with unsqueeze
x_unsqueezed = x_squeezed.unsqueeze(dim=0)
print(f"\nNew tensor: {x_unsqueezed}")
print(f"New shape: {x_unsqueezed.shape}")

Previous tensor: tensor([5., 2., 3., 4., 5., 6., 7.])
Previous shape: torch.Size([7])

New tensor: tensor([[5., 2., 3., 4., 5., 6., 7.]])
New shape: torch.Size([1, 7])


In [47]:
# Create tensor with specific shape
x_original = torch.rand(size=(224, 224, 3))

# Permute the original tensor to rearrange the axis order
x_permuted = x_original.permute(2, 0, 1) # shifts axis 0->1, 1->2, 2->0

print(f"Previous shape: {x_original.shape}")
print(f"New shape: {x_permuted.shape}")

Previous shape: torch.Size([224, 224, 3])
New shape: torch.Size([3, 224, 224])


In [39]:
# Create a tensor with a size of (3, 4)
tensor = torch.randn(3, 4)
print("Original tensor shape:", tensor.shape)

# Apply unsqueeze to add a dimension at position 0
unsqueezed_tensor = tensor.unsqueeze(0)
print("After unsqueeze at 0:", unsqueezed_tensor.shape)

# Apply unsqueeze to add a dimension at position 2
unsqueezed_tensor_1 = tensor.unsqueeze(1)
print("After unsqueeze at 1:", unsqueezed_tensor_1.shape)

# Apply unsqueeze to add a dimension at position 2
unsqueezed_tensor_2 = tensor.unsqueeze(2)
print("After unsqueeze at 2:", unsqueezed_tensor_2.shape)

Original tensor shape: torch.Size([3, 4])
After unsqueeze at 0: torch.Size([1, 3, 4])
After unsqueeze at 1: torch.Size([3, 1, 4])
After unsqueeze at 2: torch.Size([3, 4, 1])
